[package]
name = "benchmark"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thunderdome = { path = ".." }

criterion = "0.3.6"
rand = "0.8.5"

[[bench]]
name = "primary"
harness = false